export const colors = {
  appBg        : "#F2F2F2",
  pageBg       : "#F2F2F2",
  cardBg       : "#E0F5EC",
  cardBgDark   : "#C8EDD9",
  white        : "#FFFFFF",
  primary      : "#1B6B3A",
  primaryDark  : "#145229",
  primaryLight : "#2E8B57",
  accent       : "#3DAB6E",
  text         : "#1A1A1A",
  textLight    : "#6B6B6B",
  textMuted    : "#9E9E9E",
  textGreen    : "#1B6B3A",
  border       : "#B2DFC5",
  borderLight  : "#D4EFE0",
  drought      : "#E65100",
  droughtBg    : "#FFF3E0",
  droughtBorder: "#FF9800",
  pest         : "#B71C1C",
  pestBg       : "#FCE4EC",
  pestBorder   : "#F44336",
  healthy      : "#1B6B3A",
  healthyBg    : "#E0F5EC",
  healthyBorder: "#2E8B57",
};

export const CLASS_COLORS = {
  Drought        : { bg: "#FFF3E0", text: "#E65100", border: "#FF9800" },
  PestInfestation: { bg: "#FCE4EC", text: "#B71C1C", border: "#F44336" },
  Healthy        : { bg: "#E0F5EC", text: "#1B6B3A", border: "#2E8B57" },
};

// FontAwesome icon names for each class
export const CLASS_FA_ICONS = {
  Drought        : "sun",
  PestInfestation: "bug",
  Healthy        : "leaf",
};

export const STRESS_DATA = {
  Drought: {
    title      : "Drought Stress",
    icon       : "sun",
    color      : "#E65100",
    bg         : "#FFF3E0",
    border     : "#FF9800",
    description: "Drought stress occurs when rice plants do not receive sufficient water. It causes wilting, browning of leaf tips, and reduced growth.",
    symptoms   : [
      "Brown or yellowish leaf tips",
      "Wilting and drooping leaves",
      "Dry, crispy leaf edges",
      "Stunted plant growth",
      "Rolling of leaves inward",
    ],
    recommendations: [
      "Increase irrigation frequency immediately",
      "Check and repair irrigation system",
      "Apply mulching to retain soil moisture",
      "Monitor soil moisture levels daily",
      "Avoid fertilizing during drought stress",
    ],
    treatments: [
      "Flood irrigation if available",
      "Install drip irrigation system",
      "Apply anti-transpirant spray",
      "Use drought-tolerant rice varieties for next planting",
      "Consult local agricultural extension for water management",
    ],
    severity: "Moderate to Severe",
  },
  PestInfestation: {
    title      : "Pest Infestation",
    icon       : "bug",
    color      : "#B71C1C",
    bg         : "#FCE4EC",
    border     : "#F44336",
    description: "Pest infestation occurs when insects attack rice plants, causing physical damage to leaves, stems, and grains. Common pests include stem borers, leafhoppers, and leafrollers.",
    symptoms   : [
      "Irregular holes in leaves",
      "Rolled or folded leaves",
      "White or silvery streaks on leaves",
      "Dead hearts (wilted central shoot)",
      "Visible insects, eggs, or larvae",
      "Brown discoloration from feeding damage",
    ],
    recommendations: [
      "Inspect plants closely for insects and eggs",
      "Apply appropriate pesticide immediately",
      "Monitor surrounding plants for spread",
      "Remove and destroy heavily infested plants",
      "Set up light traps for night-flying insects",
    ],
    treatments: [
      "Apply systemic insecticide (consult agronomist for type)",
      "Use biological control agents (Trichogramma wasps)",
      "Apply neem-based organic pesticide",
      "Drain field temporarily to expose soil-dwelling pests",
      "Consult local agronomist for pesticide recommendation",
    ],
    severity: "Moderate to Severe",
  },
  Healthy: {
    title      : "Healthy Plant",
    icon       : "leaf",
    color      : "#1B6B3A",
    bg         : "#E0F5EC",
    border     : "#2E8B57",
    description: "Your rice plant appears healthy with no visible stress symptoms. Continue regular monitoring and maintenance to keep your plants in good condition.",
    symptoms   : [
      "Vibrant green leaf color",
      "No holes or physical damage",
      "Upright and firm plant structure",
      "Normal leaf texture and appearance",
    ],
    recommendations: [
      "Continue regular irrigation schedule",
      "Apply balanced fertilizer as scheduled",
      "Monitor weekly for early signs of stress",
      "Maintain proper plant spacing",
      "Keep field free of weeds",
    ],
    treatments: [
      "No treatment needed at this time",
      "Continue preventive pest management",
      "Maintain optimal water level in field",
      "Apply foliar nutrients if needed",
    ],
    severity: "None",
  },
};